/**
 * Created with JetBrains PhpStorm.
 * User: xuheng
 * Date: 12-8-8
 * Time: 下午2:00
 * To change this template use File | Settings | File Templates.
 */
var templates = [
    
    {
        "pre":"pre4.png",
        'title':lang.t,
        'preHtml':'活动模板',
        'html':'<div class="de-box"><div class="de-bt"><div class="de-btc">购买须知</div></div><div class="de-bc"><div class="de-row"><div class="de-rowt">商品有效期</div><div class="de-rowc">2014.01.01——2014.12.31</div></div><div class="de-row"><div class="de-rowt">使用时间</div><div class="de-rowc">每日11：00—14：00 17：00—22：00周末、法定节假日通用</div></div><div class="de-row"><div class="de-rowt">预约提醒</div><div class="de-rowc">无需预约，咨询请致电商家</div></div><div class="de-row"><div class="de-rowt">使用规则</div><div class="de-rowc"><div class="de-rowd">持汽十二变会员铭牌即可按照优惠价进店消费</div><div class="de-rowd">汽十二变用户不可同时享受商家其他优惠</div><div class="de-rowd">免费提供储物柜</div><div class="de-rowd">提供免费洗浴；免费提供洗浴用品：毛巾、汗蒸服等一次性洗浴用品</div><div class="de-rowd">不允许自带酒水，小吃！</div><div class="de-rowd">团购用户不可同时享受商家其他优惠</div><div class="de-rowd">免费提供10个停车位</div><div class="de-rowd">美团券密码一旦验证即代表消费成功，不可申请“随时退款”和“过期退款”，请您合理安排验证时间</div></div></div></div><div class="de-bt"><div class="de-btc">套餐情况</div></div><div class="de-bt2"><div class="de-btc2">套餐情况</div></div><div class="de-table"><div class="de-tr"><div class="de-td1">套餐内容</div><div class="de-td2">单价</div><div class="de-td2">数量</div><div class="de-td3">小计</div></div><div class="de-tc"><div class="de-td1">番茄米线</div><div class="de-td2">￥27</div><div class="de-td2">1份</div><div class="de-td3">￥27</div></div><div class="de-tc"><div class="de-td1">番茄米线</div><div class="de-td2">￥27</div><div class="de-td2">1份</div><div class="de-td3">￥27</div></div><div class="de-tc"><div class="de-td1">番茄米线</div><div class="de-td2">￥27</div><div class="de-td2">1份</div><div class="de-td3">￥27</div></div><div class="de-tc"><div class="de-td1">番茄米线</div><div class="de-td2">￥27</div><div class="de-td2">1份</div><div class="de-td3">￥27</div></div><div class="de-tc"><div class="de-td1">番茄米线</div><div class="de-td2">￥27</div><div class="de-td2">1份</div><div class="de-td3">￥27</div></div><div class="de-tc"><div class="de-td4">总计：￥227</div></div><div class="de-tc"><div class="de-td4">汽十二变会员价：<strong>￥100</strong></div></div></div><div class="de-bt"><div class="de-btc">商品详情</div></div><div class="de-bt2"><div class="de-btc2">商品详情</div></div><div class="de-xq"><div class="de-wz">肉类：特级五花肉、精选梅花肉、培根金针菇卷、鸡腿肉、鸡心、韩式烤肠、鸡柳串、鱼豆腐串等</div><div class="de-pic"><img src="images/deal1.jpg" /></div><div class="de-wz">肉类：特级五花肉、精选梅花肉、培根金针菇卷、鸡腿肉、鸡心、韩式烤肠、鸡柳串、鱼豆腐串等</div><div class="de-pic"><img src="images/deal1.jpg" /></div><div class="de-wz">肉类：特级五花肉、精选梅花肉、培根金针菇卷、鸡腿肉、鸡心、韩式烤肠、鸡柳串、鱼豆腐串等</div><div class="de-pic"><img src="images/deal1.jpg" /></div></div><div class="de-bt2"><div class="de-btc2">商家简介</div></div><div class="de-xq"><div class="de-wz">513669995你懂得修改1</div><div class="de-pic"><img src="images/deal1.jpg" /></div></div></div>'
    },
    {
        "pre":"pre4.png",
        'title':lang.t,
        'preHtml':'任务模板',
        'html':'<div class="de-box"><div class="de-bt"><div class="de-btc">车主须知</div></div><div class="de-bc"><div class="de-row"><div class="de-rowt">车辆要求</div><div class="de-rowc">工具车,面包车,微型车除外,6万元以上浅色系私家车</div></div><div class="de-row"><div class="de-rowt">薪金分配</div><div class="de-rowc">合同到期后统一发送:400元现金</div></div><div class="de-row"><div class="de-rowt">代金卷使用说明</div><div class="de-rowc">在所有贴有【中国银联】POS机上都可以使用，超时购物，加油均可</div></div><div class="de-row"><div class="de-rowt">任务规则及要求</div><div class="de-rowc"><div class="de-rowd">1.报名时请大家注意自己的个人资料是否完善，避免因车辆资料不全或不真实而错过活动</div><div class="de-rowd">2.有活动在车身的车主请勿报名</div><div class="de-rowd">3.报名时请大家特别注意自己的个人资料是否完善，避免因车辆资料不全或不真实而错过活动</div><div class="de-rowd">4、提供免费洗浴；免费提供洗浴用品：毛巾、汗蒸服等一次性洗浴用品</div><div class="de-rowd">5、不允许自带酒水，小吃！</div><div class="de-rowd">6、团购用户不可同时享受商家其他优惠</div></div></div></div><div class="de-bt2"><div class="de-btc2">车贴效果及要求</div></div><div class="de-xq"><div class="de-wz">车贴整体效果</div><div class="de-pic"><img src="images/deal1.jpg" /></div><div class="de-wz">车贴要求</div><div class="de-pic"><img src="images/deal1.jpg" /></div></div><div class="de-bt2"><div class="de-btc2">商家简介</div></div><div class="de-xq"><div class="de-wz">商家简介商家简介商家简介商家简介商家简介商家简介</div><div class="de-pic"><img src="images/deal1.jpg" /></div></div></div>'
    }
];